name: deploy-container
on:
  push:
    branches:
      - master
    paths:
      - "mfp/mfp/packages/container/**"

defaults:
  run:
    working-directory: mfp/mfp/packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: jithesh02/action-aws-cli@v1.1
      - run: aws s3 sync dist s3:/mfe-dashboard26062002/container/latest
        env:
          AWS_ACCESS_KEY_ID: AKIA4XME5VGS246ZXCY7
          AWS_SECRET_ACCESS_KEY: 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
          AWS_DEFAULT_REGION: ""
